app:
  port: 3101
  host: 0.0.0.0
  logLevel: info

db:
  host: localhost
  port: 5432
  name: aa_task_tracker
  user: postgres
  pass: postgres

services:
  authUrl: 0.0.0.0:3100

rabbitConnectionUrl: 'amqp://localhost'
eventHandlingAttempt: 3
attempt:
  count: 3
  delay: 1000
