PATCH http://localhost:3101/tasks/assign
Content-Type: application/json
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjU4NzYyODYsImV4cCI6MTY2NzE3MjI4Nn0.bE0qzSLqP30tYY6XWxjwXxisapOcHAVWV9GgXB3BHFU

{
  "userId": "1",
  "taskId": "2"
}
