PATCH http://localhost:3101/tasks/assign
Content-Type: application/json
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjY1Mjc1MzgsImV4cCI6MTY2NjYxMzkzOH0.kacWwnVBQgy95aHmIH7c5wjhXkETzTTdP3MRkZn9_oA

{
  "userId": "1",
  "taskId": "19"
}
