PATCH http://localhost:3101/tasks/complete
Content-Type: application/json
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjY1ODcyMTc4LCJleHAiOjE2NjcxNjgxNzh9.-RirCHH8f-2C7p0S_HP94cfs3QEy9epFQoTSszbWs8I

{
  "taskId": "4"
}
