POST http://localhost:3101/tasks
Content-Type: application/json
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjcxNjE4OTksImV4cCI6MTY2NzI0ODI5OX0.STFrVjzLOOEFvhGAJAm4LOhCdR6n39-11Tk0_cQpiRY

{
  "userId": "1",
  "title": "[OG-1] Отправить отчетность в налоговую"
}
