GET http://localhost:3101/tasks?limit=15&offset=0
Content-Type: application/json
Accept: application/json
# admin
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjY1NzI4ODkwLCJleHAiOjE2NjU4MTUyOTB9.M5eVnZaBTk9MMLWW6gb-lwFnVOOKy12z_k_1UPM7WNw
# user
