POST http://localhost:3100/users/change_password
Content-Type: application/json
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjYzNzU2NzEsImV4cCI6MTY2NjQ2MjA3MX0.xa9eEAIj0Twsf9WLTZTGHdPtLeiz0obtyDI9rmU_L74

{
  "password": "123456"
}
