GET http://localhost:3100/users?limit=1&offset=0
Content-Type: application/json
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjY1OTIxMjQ0LCJleHAiOjE2NjYwMDc2NDR9.eLQLZgpDxVHDDxasosUlatoI1YMAJeETMVDnyinQjUM
