GET http://localhost:3100/users?limit=1&offset=0
Content-Type: application/json
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjY0ODczMzg0LCJleHAiOjE2NjQ5NTk3ODR9.Py4fMvnqiSzVeIKXN1M7_3o-yAkdBAbRYA4ORwreCYU
